version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.3
  slack: circleci/slack@4.9.3

  # Always take the latest version of the orb, this allows us to
  # run specs against Solidus supported versions only without the need
  # to change this configuration every time a Solidus version is released
  # or goes EOL.
  solidusio_extensions: solidusio/extensions@volatile

commands:
  libvips:
    steps:
      - run:
          name: Install libvips
          command: sudo apt-get install -y libvips

  notify:
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1
          branch_pattern: master, v[0-9]+\.[0-9]+

jobs:
  run-specs-with-postgres:
    executor: solidusio_extensions/postgres
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - libvips
      - solidusio_extensions/run-tests-solidus-master
      - solidusio_extensions/store-test-results
      - notify
  run-specs-with-mysql:
    executor: solidusio_extensions/mysql
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - libvips
      - solidusio_extensions/run-tests-solidus-master
      - solidusio_extensions/store-test-results
      - notify
  lint-code:
    executor: solidusio_extensions/sqlite-memory
    steps:
      - solidusio_extensions/lint-code
      - notify

workflows:
  "Run specs on supported Solidus versions":
    jobs:
      - run-specs-with-postgres:
          context: slack-secrets
      - run-specs-with-mysql:
          context: slack-secrets

  "Weekly run specs against master":
    triggers:
      - schedule:
          cron: "0 0 * * 4" # every Thursday
          filters:
            branches:
              only:
                - master
    jobs:
      - run-specs-with-postgres:
          context: slack-secrets
      - run-specs-with-mysql:
          context: slack-secrets
