version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.3

  # Always take the latest version of the orb, this allows us to
  # run specs against Solidus supported versions only without the need
  # to change this configuration every time a Solidus version is released
  # or goes EOL.
  solidusio_extensions: solidusio/extensions@volatile

commands:
  libvips:
    steps:
      - run:
          name: Install libvips
          command: |
            sudo apt-get update
            sudo apt-get install -yq libvips-dev

jobs:
  run-specs:
    parameters:
      db:
        type: string
        default: "postgres"
      ruby:
        type: string
        default: "3.2"
    executor:
      name: solidusio_extensions/<< parameters.db >>
      ruby_version: << parameters.ruby >>
    steps:
      - checkout
      - browser-tools/install-chrome
      - libvips
      - solidusio_extensions/run-tests-solidus-main

workflows:
  "Run specs on Solidus main":
    jobs:
      - run-specs:
          name: &name "run-specs-solidus-main-ruby-<< matrix.ruby >>-db-<< matrix.db >>"
          matrix:
            parameters: { ruby: ["3.2"], db: ["postgres"] }
      - run-specs:
          name: &name "run-specs-solidus-main-ruby-<< matrix.ruby >>-db-<< matrix.db >>"
          matrix:
            parameters: { ruby: ["3.1"], db: ["mysql"] }
      - run-specs:
          name: &name "run-specs-solidus-main-ruby-<< matrix.ruby >>-db-<< matrix.db >>"
          matrix:
            parameters: { ruby: ["3.0"], db: ["sqlite"] }

  "Weekly run specs against main":
    triggers:
      - schedule:
          cron: "0 0 * * 4" # every Thursday
          filters:
            branches:
              only:
                - main
    jobs:
      - run-specs:
          name: *name
          matrix:
            parameters: { ruby: ["3.2"], db: ["postgres"] }
